### ISSUE TITLE
Click on SVGView not working

### ISSUE THREAD

**Issue by Lupurus** [exyte/Macaw#228] opened 2017-11-26 01:29 UTC
I'm using the `SVGView` in a `NSTableView` and a `NSOutlineView`. Selecting by clicking on the row is working, but the row is not getting selected, when pressing on the SVGView.

**Comment by Lupurus** [comment] 2017-11-26 02:22
The problem is, that the `NSClickGestureRecognizer` delays the events. So if the tap is recognized and doesn't fail, the mouse click is not sent to the view. See https://developer.apple.com/documentation/appkit/nsclickgesturerecognizer

I don't really understand (yet), what you're doing with the TapRecognizer, but can we set the `delaysPrimaryMouseButtonEvents` to false? If so, the above written problem works.

**Comment by Lupurus** [comment] 2017-11-26 19:50
So I checked the code and that's, what I've found out and what I suppose as the solution:

1) In the `MacawView` you install all the GestureRecognizers in `initializeView`.
2) If the `self.node` in the view doesn't have any handlers for the gestures (for example a tapHandler), the gesture action will only `return`
There is the problem: The click is recognized and will be send to the tapHandler, but nothing happens (only return) and because the recognition didn't fail, cocoa cannot handle the click.

My suggestion:
If there is no handler, I would do the following:
In `MacawView` I added the following code to `open var node: Node = Group() { ... didSet {`

```
didSet {
    nodesMap.add(node, view: self)
    // remove TapRecognizer, if there is no TapHandler
    if node.tapHandlers.count == 0 {
        self.gestureRecognizers = self.gestureRecognizers.filter { !($0 is MTapGestureRecognizer) }
    }
    self.renderer?.dispose()
    ...
```

**Comment by Lupurus** [comment] 2017-12-03 17:21
You're right. I just ran into this problem, as I set a TapHandler ;) It's really a headaching problem... The best way would be to add a `GestureRecognizer` just in that case, that it's added to the `Node`, but in this case you don't have access to the `MacawView`.

My actual workaround is now, that I call the `removeGestureRecognizers()` on all SVGViews in my OutlineView. Luckily, this function is not private :)

**Comment by f3dm76** [comment] 2018-07-24 09:31
Hello Lupurus,
It's been a while, sorry. In case you are still interested, could you please provide your code, where we could see the bug? I tried putting some `SVGView`s in cells of a table, but `didSelectCellForRow` is working fine when clicking on them

**Comment by ystrot** [comment] 2018-10-02 10:57
Closing this issue once we can't reproduce it. Please reopen it with a sample if necessary.

**Closed by ystrot** 2018-10-02 10:57 UTC

**Comment by zhaoweiyan123** [comment] 2019-04-25 02:35
Hi Lupurus you just meet the issue in the Macaw and now , i meet the problem like you and  the problem is that i use  the NSView and NSOulineView . i add the gusture even in the nsview , NSClickGestureRecognizer delays the events but  the event could be delay . i dont know why
