### ISSUE TITLE
Macaw.image.srcVar do not change image on change src

### ISSUE THREAD

**Issue by mkdk** [exyte/Macaw#491] opened 2018-10-18 13:41 UTC
Need help urgent! :( 
On xcode 9 our code was worked well, but after start working with xcode 10 Macaw.image.srcVar do not change image if we change srcVar on the fly.

Maybe I misunderstood something, but I expecting that if I we change scrVar it will rerender image in the node....

here is code example:
```
substrate.onTap { _ in
       if !self.pickedSeats.contains(index) {
                self.pickedSeats.insert(index)
                seatView.sView.srcVar.value = SeatType.picked.getSrc()
                seatView.sView.opacityVar.animate(to: 0.9)
                seatView.text.font = Font(name: "MullerExtraBold", size: 13)
                self.delegate?.seatPicked(id: seat.id, unselect: false, publicPid: seat.publicPid)
        } else {
                self.pickedSeats.remove(index)
                seatView.sView.srcVar.value = seat.type.getSrc()
                seatView.text.font = Font(name: "MullerMedium", size: 12)
                self.delegate?.seatPicked(id: seat.id, unselect: true, publicPid: seat.publicPid)
           }
   }
```

**> seatView.sView.srcVar.value = SeatType.picked.getSrc()**
**> seatView.sView.srcVar.value = seat.type.getSrc()**

**Comment by ystrot** [comment] 2018-10-18 14:06
First of all, it's better to use 
```swift
seatView.sView.src = ...
```
instead of
```swift
seatView.sView.srcVar.value = ...
```

However both should work.

Can you create a sample project demonstration this issue? Otherwise you need to debug Macaw code: (check out `Image.image()` which create corresponding `UIImage`). Most probably new image can't be loaded for some reason.

**Comment by mkdk** [comment] 2018-10-18 14:10
Thank you for your answer, if it will not work tomorrow i'll create demonstration project

**Comment by ystrot** [comment] 2018-10-18 14:12
Thanks, it will be really useful.

**Comment by mkdk** [comment] 2018-10-19 10:05
@ystrot i create sample project demonstration for issue. there exactly same enviroment which in our production app. thank you for your time. https://github.com/mkdk/demomacawissue-491

**Comment by ystrot** [comment] 2018-10-22 09:43
Looks like I found source of this issue. Strange it works for you before, because the problem reproduced on Xcode 9 as well. Anyway, should be fixed in the nearest time.

**Comment by ystrot** [comment] 2018-10-22 09:45
Looks like I found source of this issue. Strange it worked for you before, because this issue reproduced on Xcode 9 as well. Anyway, should be fixed in the nearest time.

**Comment by mkdk** [comment] 2018-10-22 10:43
@ystrot thanks a lot!

**Closed** 2018-10-22 11:28 UTC

**Comment by ystrot** [comment] 2018-10-22 11:32
I've pushed a fix. Please try Macaw from master branch.

**Comment by mkdk** [comment] 2018-10-22 11:59
@ystrot It works now. Thank for your time!
