### ISSUE TITLE
Binary operator '==' cannot be applied to two 'Fill' operands

### ISSUE THREAD

**Issue by 008v** [exyte/Macaw#424] opened 2018-06-15 08:09 UTC
Binary operator '==' cannot be applied to two 'Fill' operands

**Comment by 008v** [comment] 2018-06-15 08:10
Is there any way to serialize the fill object?

**Comment by 008v** [comment] 2018-06-15 08:42
extension Fill: Equatable {
    public static func == (lhs: Fill, rhs: Fill) -> Bool {
        if let lColor = lhs as? Color, let rColor = rhs as? Color {
            if lColor == rColor {
                return true
            }
        }
        if let lLinearGradient = lhs as? LinearGradient, let rLinearGradient = rhs as? LinearGradient {
            return (lLinearGradient.x1 == rLinearGradient.x1 && lLinearGradient.x2 == rLinearGradient.x2 && lLinearGradient.y1 == rLinearGradient.y1 && lLinearGradient.y2 == rLinearGradient.y2 && lLinearGradient.userSpace == rLinearGradient.userSpace && lLinearGradient.stops.count == rLinearGradient.stops.count)
        }
        return false
    }
    
    public static func != (lhs: Fill, rhs: Fill) -> Bool {
        if let lColor = lhs as? Color, let rColor = rhs as? Color {
            if lColor == rColor {
                return false
            }
        }
        if let lLinearGradient = lhs as? LinearGradient, let rLinearGradient = rhs as? LinearGradient {
            return !(lLinearGradient.x1 == rLinearGradient.x1 && lLinearGradient.x2 == rLinearGradient.x2 && lLinearGradient.y1 == rLinearGradient.y1 && lLinearGradient.y2 == rLinearGradient.y2 && lLinearGradient.userSpace == rLinearGradient.userSpace && lLinearGradient.stops.count == rLinearGradient.stops.count)
        }
        return true
    }
}

**Comment by 008v** [comment] 2018-06-15 08:42
`extension Fill: Equatable {
    public static func == (lhs: Fill, rhs: Fill) -> Bool {
        if let lColor = lhs as? Color, let rColor = rhs as? Color {
            if lColor == rColor {
                return true
            }
        }
        if let lLinearGradient = lhs as? LinearGradient, let rLinearGradient = rhs as? LinearGradient {
            return (lLinearGradient.x1 == rLinearGradient.x1 && lLinearGradient.x2 == rLinearGradient.x2 && lLinearGradient.y1 == rLinearGradient.y1 && lLinearGradient.y2 == rLinearGradient.y2 && lLinearGradient.userSpace == rLinearGradient.userSpace && lLinearGradient.stops.count == rLinearGradient.stops.count)
        }
        return false
    }
    
    public static func != (lhs: Fill, rhs: Fill) -> Bool {
        if let lColor = lhs as? Color, let rColor = rhs as? Color {
            if lColor == rColor {
                return false
            }
        }
        if let lLinearGradient = lhs as? LinearGradient, let rLinearGradient = rhs as? LinearGradient {
            return !(lLinearGradient.x1 == rLinearGradient.x1 && lLinearGradient.x2 == rLinearGradient.x2 && lLinearGradient.y1 == rLinearGradient.y1 && lLinearGradient.y2 == rLinearGradient.y2 && lLinearGradient.userSpace == rLinearGradient.userSpace && lLinearGradient.stops.count == rLinearGradient.stops.count)
        }
        return true
    }
}`

**Comment by 008v** [comment] 2018-06-15 09:33
Only the Color class in Fill's subclass provides a Equatable method.

**Comment by ystrot** [comment] 2018-06-26 07:13
Makes sense, we'll implement it in the next release.

**Comment by amarunko** [comment] 2018-08-23 07:49
@008v, the issue is fixed in the master branch, you're welcome to check it out.

**Closed** 2018-10-02 10:54 UTC
